version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    reviewers:
      - 'withinjoel'
    ignore:
      - dependency-name: 'electron-builder'
        versions: ['>=26.12.0']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    reviewers:
      - 'withinjoel'
