// This is the common data entries used in import/export of Joanium.
export const KNOWN_DATA_ENTRIES = [
  'Agents',
  'Avatar.avif',
  'Avatar.bmp',
  'Avatar.gif',
  'Avatar.jpeg',
  'Avatar.jpg',
  'Avatar.png',
  'Avatar.webp',
  'Browsing',
  'ChannelMessages',
  'Channels.json',
  'Chats',
  'Dreams',
  'Logs',
  'Memories',
  'MCPServers.json',
  'Models',
  'Projects',
  'Screenshots',
  'Security.json',
  'System.json',
  'Templates',
  'Usage',
  'Usage.json',
  'User.json',
];
