export const GITLAB_TOOLS = [
  {
    name: 'gitlab_list_repos',
    description: "List the user's GitLab repositories.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_get_issues',
    description: 'Get issues for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_pull_requests',
    description: 'Get merge requests for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_file',
    description: 'Load the contents of a file from a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      filePath: {
        type: 'string',
        required: !0,
        description: 'Path to the file inside the repository',
      },
    },
  },
  {
    name: 'gitlab_get_file_tree',
    description: 'Get the file tree of a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_notifications',
    description: 'Get pending GitLab todos/notifications.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_get_commits',
    description: 'Get recent commits for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_create_issue',
    description: 'Create a new issue in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      title: { type: 'string', required: !0, description: 'Issue title' },
      body: { type: 'string', required: !1, description: 'Issue body in markdown' },
      labels: { type: 'string', required: !1, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'gitlab_close_issue',
    description: 'Close an issue in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
    },
  },
  {
    name: 'gitlab_reopen_issue',
    description: 'Reopen a closed issue in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
    },
  },
  {
    name: 'gitlab_comment_on_issue',
    description: 'Comment on a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      body: { type: 'string', required: !0, description: 'Comment body in markdown' },
    },
  },
  {
    name: 'gitlab_list_branches',
    description: 'List branches in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_releases',
    description: 'Get recent releases for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      count: {
        type: 'number',
        required: !1,
        description: 'Number of releases to fetch (default 5, max 20)',
      },
    },
  },
  {
    name: 'gitlab_star_repo',
    description: 'Star or unstar a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      action: { type: 'string', required: !1, description: 'star (default) or unstar' },
    },
  },
  {
    name: 'gitlab_create_gist',
    description: 'Create a GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      description: { type: 'string', required: !1, description: 'Snippet description' },
      filename: { type: 'string', required: !0, description: 'Primary file name' },
      content: { type: 'string', required: !0, description: 'Primary file content' },
      public: { type: 'boolean', required: !1, description: 'Set true to make the snippet public' },
    },
  },
  {
    name: 'gitlab_mark_notifications_read',
    description: 'Mark all GitLab todos as done.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_get_repo_stats',
    description: 'Get repository statistics such as stars, forks, watchers, and open issues.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_create_pull_request',
    description: 'Create a new merge request in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      title: { type: 'string', required: !0, description: 'Merge request title' },
      head: { type: 'string', required: !0, description: 'Source branch' },
      base: { type: 'string', required: !0, description: 'Target branch' },
      body: { type: 'string', required: !1, description: 'Merge request description in markdown' },
      draft: {
        type: 'boolean',
        required: !1,
        description: 'Set true to open as a draft merge request',
      },
    },
  },
  {
    name: 'gitlab_merge_pull_request',
    description: 'Merge a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      merge_method: { type: 'string', required: !1, description: 'merge, squash, or rebase' },
      commit_title: {
        type: 'string',
        required: !1,
        description: 'Optional custom merge commit title',
      },
    },
  },
  {
    name: 'gitlab_close_pull_request',
    description: 'Close a merge request without merging it.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_add_labels',
    description: 'Add labels to a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      labels: { type: 'string', required: !0, description: 'Comma-separated label names' },
    },
  },
  {
    name: 'gitlab_add_assignees',
    description: 'Assign GitLab users to an issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      assignees: { type: 'string', required: !0, description: 'Comma-separated GitLab usernames' },
    },
  },
  {
    name: 'gitlab_trigger_workflow',
    description: 'Trigger a GitLab CI/CD pipeline.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      workflow_id: { type: 'string', required: !0, description: 'Pipeline schedule ID' },
      ref: { type: 'string', required: !1, description: 'Branch or tag to run the pipeline on' },
      inputs: { type: 'string', required: !1, description: 'JSON string of pipeline variables' },
    },
  },
  {
    name: 'gitlab_get_latest_workflow_run',
    description: 'Get the latest run for a GitLab CI/CD pipeline.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      workflow_id: { type: 'string', required: !0, description: 'Pipeline schedule ID' },
      branch: { type: 'string', required: !1, description: 'Optional branch filter' },
    },
  },
  {
    name: 'gitlab_get_latest_release',
    description: 'Get the latest published release for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_notification_count',
    description: 'Count pending GitLab todos grouped by repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_load_repo_context',
    description: 'Load a repository tree and selected file contents for deeper code understanding.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      focus_paths: {
        type: 'string',
        required: !1,
        description: 'Comma-separated path prefixes to focus on',
      },
      max_files: {
        type: 'number',
        required: !1,
        description: 'Maximum number of files to load (default 20, max 40)',
      },
    },
  },
  {
    name: 'gitlab_search_code',
    description: 'Search code in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      query: { type: 'string', required: !0, description: 'Search query' },
    },
  },
  {
    name: 'gitlab_get_pr_diff',
    description: 'Get the unified diff of a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_review_pr',
    description: 'Post a code review on a GitLab merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      body: { type: 'string', required: !0, description: 'Overall review body' },
      verdict: {
        type: 'string',
        required: !1,
        description: 'APPROVE, REQUEST_CHANGES, or COMMENT',
      },
      inline_comments: {
        type: 'string',
        required: !1,
        description: 'JSON array of inline comments',
      },
    },
  },
  {
    name: 'gitlab_get_pr_details',
    description: 'Get detailed merge request metadata.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_pr_checks',
    description: 'Get CI and pipeline status for a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_pr_comments',
    description: 'Load inline review comments for a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_workflow_runs',
    description: 'List recent pipeline runs for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab owner or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      branch: { type: 'string', required: !1, description: 'Optional branch filter' },
      event: { type: 'string', required: !1, description: 'Optional pipeline source filter' },
      per_page: {
        type: 'number',
        required: !1,
        description: 'Maximum number of runs to return (default 20)',
      },
    },
  },
  {
    name: 'gitlab_get_readme',
    description: 'Fetch the README of a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_issue_details',
    description: 'Get full details of a single GitLab issue.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
    },
  },
  {
    name: 'gitlab_update_issue',
    description: 'Update the title, body, state, labels, or assignees of a GitLab issue.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
      title: { type: 'string', required: !1, description: 'New title' },
      body: { type: 'string', required: !1, description: 'New body in markdown' },
      state: { type: 'string', required: !1, description: 'open or closed' },
      labels: { type: 'string', required: !1, description: 'Comma-separated label names to set' },
      assignees: {
        type: 'string',
        required: !1,
        description: 'Comma-separated GitLab usernames to set',
      },
    },
  },
  {
    name: 'gitlab_get_contributors',
    description: 'List contributors to a GitLab repository sorted by commit count.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_languages',
    description: 'Get the programming language breakdown for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_topics',
    description: 'Get the topic tags applied to a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_milestones',
    description: 'List milestones for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      state: { type: 'string', required: !1, description: 'open (default), closed, or all' },
    },
  },
  {
    name: 'gitlab_create_milestone',
    description: 'Create a milestone in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      title: { type: 'string', required: !0, description: 'Milestone title' },
      description: { type: 'string', required: !1, description: 'Optional description' },
      due_on: {
        type: 'string',
        required: !1,
        description: 'ISO 8601 due date, e.g. 2025-12-31T00:00:00Z',
      },
    },
  },
  {
    name: 'gitlab_create_branch',
    description: 'Create a new branch in a repository from a given commit SHA.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      branch_name: { type: 'string', required: !0, description: 'New branch name' },
      sha: { type: 'string', required: !0, description: 'Commit SHA to branch from' },
    },
  },
  {
    name: 'gitlab_delete_branch',
    description: 'Delete a branch from a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      branch_name: { type: 'string', required: !0, description: 'Branch to delete' },
    },
  },
  {
    name: 'gitlab_get_forks',
    description: 'List forks of a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_stargazers',
    description: 'List users who have starred a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_collaborators',
    description: 'List members of a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_compare_branches',
    description: 'Compare two branches or commits and show ahead/behind status and changed files.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      base: { type: 'string', required: !0, description: 'Base branch or SHA' },
      head: { type: 'string', required: !0, description: 'Head branch or SHA to compare' },
    },
  },
  {
    name: 'gitlab_get_gists',
    description: "List the authenticated user's GitLab Snippets.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_get_traffic_views',
    description: 'Get view traffic stats for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_request_reviewers',
    description: 'Request reviewers for a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      reviewers: { type: 'string', required: !1, description: 'Comma-separated GitLab usernames' },
      team_reviewers: { type: 'string', required: !1, description: 'Comma-separated team slugs' },
    },
  },
  {
    name: 'gitlab_get_pr_files',
    description: 'List the files changed in a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_list_pr_reviews',
    description: 'List all approvals submitted on a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_user_info',
    description: 'Get public profile information for any GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username to look up' },
    },
  },
  {
    name: 'gitlab_search_repos',
    description: 'Search GitLab repositories globally by keyword.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      query: { type: 'string', required: !0, description: 'Search query' },
      count: {
        type: 'number',
        required: !1,
        description: 'Max results to return (default 20, max 50)',
      },
    },
  },
  {
    name: 'gitlab_search_issues',
    description: 'Search issues across GitLab.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      query: { type: 'string', required: !0, description: 'Search query' },
      count: {
        type: 'number',
        required: !1,
        description: 'Max results to return (default 20, max 50)',
      },
    },
  },
  {
    name: 'gitlab_get_issue_comments',
    description: 'Get all comments on a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      count: { type: 'number', required: !1, description: 'Max comments to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_commit_details',
    description:
      'Get detailed information about a specific commit including file changes and stats.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      sha: { type: 'string', required: !0, description: 'Full or abbreviated commit SHA' },
    },
  },
  {
    name: 'gitlab_get_tags',
    description: 'List tags in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      count: { type: 'number', required: !1, description: 'Max tags to return (default 20)' },
    },
  },
  {
    name: 'gitlab_create_release',
    description: 'Create a new release in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      tag_name: {
        type: 'string',
        required: !0,
        description: 'Tag name for the release (e.g. v1.2.0)',
      },
      name: { type: 'string', required: !1, description: 'Release title (defaults to tag name)' },
      body: { type: 'string', required: !1, description: 'Release notes in markdown' },
      draft: { type: 'boolean', required: !1, description: 'Set true to create as a draft' },
      prerelease: { type: 'boolean', required: !1, description: 'Set true to mark as pre-release' },
      target_commitish: {
        type: 'string',
        required: !1,
        description: 'Branch or commit SHA to tag',
      },
    },
  },
  {
    name: 'gitlab_fork_repo',
    description:
      "Fork a GitLab repository into the authenticated user's account or a specified group.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'Owner of the repository to fork' },
      repo: { type: 'string', required: !0, description: 'Repository name to fork' },
      organization: {
        type: 'string',
        required: !1,
        description: 'Group to fork into (omit to fork into personal account)',
      },
    },
  },
  {
    name: 'gitlab_update_pull_request',
    description: 'Update the title, body, state, or target branch of a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      title: { type: 'string', required: !1, description: 'New title' },
      body: { type: 'string', required: !1, description: 'New description in markdown' },
      state: { type: 'string', required: !1, description: 'open or closed' },
      base: { type: 'string', required: !1, description: 'New target branch name' },
    },
  },
  {
    name: 'gitlab_get_labels',
    description: 'List all labels defined in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_create_label',
    description: 'Create a new label in a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      name: { type: 'string', required: !0, description: 'Label name' },
      color: { type: 'string', required: !0, description: 'Hex color without # (e.g. ff0000)' },
      description: { type: 'string', required: !1, description: 'Short description of the label' },
    },
  },
  {
    name: 'gitlab_delete_label',
    description: 'Delete a label from a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      name: { type: 'string', required: !0, description: 'Exact label name to delete' },
    },
  },
  {
    name: 'gitlab_search_users',
    description: 'Search for GitLab users.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      query: { type: 'string', required: !0, description: 'Search query' },
      count: {
        type: 'number',
        required: !1,
        description: 'Max results to return (default 20, max 50)',
      },
    },
  },
  {
    name: 'gitlab_get_user_starred',
    description: 'List repositories starred by a GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_file_commits',
    description: 'Get the commit history for a specific file in a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      file_path: {
        type: 'string',
        required: !0,
        description: 'Path to the file (e.g. src/index.js)',
      },
      count: { type: 'number', required: !1, description: 'Max commits to return (default 15)' },
    },
  },
  {
    name: 'gitlab_lock_issue',
    description: 'Lock an issue or merge request to prevent further comments.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      lock_reason: { type: 'string', required: !1, description: 'Reason for locking' },
    },
  },
  {
    name: 'gitlab_unlock_issue',
    description: 'Unlock a previously locked issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
    },
  },
  {
    name: 'gitlab_get_deployments',
    description: 'List deployments for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      count: {
        type: 'number',
        required: !1,
        description: 'Max deployments to return (default 20)',
      },
    },
  },
  {
    name: 'gitlab_get_repo_permissions',
    description: "Get a specific user's permission level in a repository.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      username: { type: 'string', required: !0, description: 'GitLab username to check' },
    },
  },
  {
    name: 'gitlab_remove_labels',
    description: 'Remove specific labels from a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      labels: {
        type: 'string',
        required: !0,
        description: 'Comma-separated label names to remove',
      },
    },
  },
  {
    name: 'gitlab_get_pr_requested_reviewers',
    description: 'Get the list of users currently requested to review a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_repo_info',
    description:
      'Get full metadata for a GitLab repository including license, visibility, and dates.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_org_repos',
    description: 'List repositories belonging to a GitLab group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      count: { type: 'number', required: !1, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'gitlab_watch_repo',
    description: 'Watch or unwatch a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      action: { type: 'string', required: !1, description: 'watch (default) or unwatch' },
    },
  },
  {
    name: 'gitlab_get_user_events',
    description: "Get a GitLab user's recent public activity events.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max events to return (default 20)' },
    },
  },
  {
    name: 'gitlab_get_repo_environments',
    description: 'List deployment environments configured for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_list_actions_secrets',
    description: 'List GitLab CI/CD variable names in a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_dependabot_alerts',
    description: 'List dependency vulnerability findings for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      state: { type: 'string', required: !1, description: 'open (default), dismissed, or fixed' },
    },
  },
  {
    name: 'gitlab_get_commits_since',
    description: 'Get commits in a repository within a date range.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      since: {
        type: 'string',
        required: !0,
        description: 'ISO 8601 start date e.g. 2024-01-01T00:00:00Z',
      },
      until: { type: 'string', required: !1, description: 'ISO 8601 end date (optional)' },
      count: { type: 'number', required: !1, description: 'Max commits to return (default 20)' },
    },
  },
  {
    name: 'gitlab_get_branch_protection',
    description: 'Get branch protection rules for a specific branch.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      branch: { type: 'string', required: !0, description: 'Branch name e.g. main' },
    },
  },
  {
    name: 'gitlab_get_user_orgs',
    description: 'List the public groups a GitLab user belongs to.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { username: { type: 'string', required: !0, description: 'GitLab username' } },
  },
  {
    name: 'gitlab_get_traffic_clones',
    description: 'Get clone traffic stats for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_community_profile',
    description: 'Get the community health profile of a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_repo_webhooks',
    description: 'List webhooks configured for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_org_members',
    description: 'List public members of a GitLab group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      count: { type: 'number', required: !1, description: 'Max members to return (default 30)' },
    },
  },
  {
    name: 'gitlab_list_org_teams',
    description: 'List subgroups in a GitLab group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      count: { type: 'number', required: !1, description: 'Max subgroups to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_team_members',
    description: 'List members of a specific subgroup within a GitLab group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      team_slug: { type: 'string', required: !0, description: 'Subgroup slug' },
      count: { type: 'number', required: !1, description: 'Max members to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_issue_reactions',
    description: 'Get emoji reactions on a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
    },
  },
  {
    name: 'gitlab_get_repo_license',
    description: 'Get the license file and metadata for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_code_frequency',
    description: 'Get weekly addition and deletion counts for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_contributor_stats',
    description: 'Get commit, addition, and deletion counts per contributor for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_commit_activity',
    description: 'Get weekly commit counts for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_punch_card',
    description: 'Get commit frequency by day of week and hour for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_repo_subscription',
    description: "Check the authenticated user's watch/subscription status for a repository.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_user_followers',
    description: 'List followers of a GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max followers to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_user_following',
    description: 'List users that a GitLab user is following.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max following to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_user_gists',
    description: 'List public snippets for a GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max snippets to return (default 20)' },
    },
  },
  {
    name: 'gitlab_get_gist_details',
    description: 'Get full details and file contents of a specific GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { gist_id: { type: 'string', required: !0, description: 'Snippet ID' } },
  },
  {
    name: 'gitlab_get_pr_commits',
    description: 'List all commits in a merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
    },
  },
  {
    name: 'gitlab_get_commit_statuses',
    description: 'Get CI/CD statuses for a specific commit ref or SHA.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      ref: { type: 'string', required: !0, description: 'Commit SHA, branch, or tag' },
    },
  },
  {
    name: 'gitlab_get_repo_pages',
    description: 'Get GitLab Pages configuration and status for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_org_info',
    description: 'Get public profile and metadata for a GitLab group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { org: { type: 'string', required: !0, description: 'GitLab group name' } },
  },
  {
    name: 'gitlab_search_commits',
    description: 'Search commits across GitLab by message, author, repo, date, etc.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      query: { type: 'string', required: !0, description: 'Search query' },
      count: {
        type: 'number',
        required: !1,
        description: 'Max results to return (default 20, max 50)',
      },
    },
  },
  {
    name: 'gitlab_get_deployment_statuses',
    description: 'Get status history for a specific deployment.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      deployment_id: { type: 'number', required: !0, description: 'Deployment ID' },
    },
  },
  {
    name: 'gitlab_get_repo_invitations',
    description: 'List pending collaboration invitations for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_rate_limit',
    description: 'Check the current GitLab API rate limit status.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_list_workflows',
    description: 'List all GitLab CI/CD pipeline schedules in a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_workflow_details',
    description: 'Get metadata for a specific GitLab CI/CD pipeline schedule.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      workflow_id: { type: 'string', required: !0, description: 'Pipeline schedule ID' },
    },
  },
  {
    name: 'gitlab_get_actions_runners',
    description: 'List CI/CD runners for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_actions_variables',
    description: 'List CI/CD variables for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_actions_cache',
    description: 'List CI/CD cache entries for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_team_repos',
    description: 'List repositories a specific subgroup has access to within a group.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      team_slug: { type: 'string', required: !0, description: 'Subgroup slug' },
      count: { type: 'number', required: !1, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_user_repos',
    description: 'List public repositories for any GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username' },
      count: { type: 'number', required: !1, description: 'Max repos to return (default 30)' },
    },
  },
  {
    name: 'gitlab_get_issue_timeline',
    description: 'Get the event timeline for a GitLab issue.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
    },
  },
  {
    name: 'gitlab_get_org_secrets',
    description: 'List group-level GitLab CI/CD variable names.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { org: { type: 'string', required: !0, description: 'GitLab group name' } },
  },
  {
    name: 'gitlab_get_single_comment',
    description: 'Get a single issue or MR comment by its ID.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      comment_id: { type: 'number', required: !0, description: 'Comment ID' },
    },
  },
  {
    name: 'gitlab_get_security_advisories',
    description: 'List vulnerability findings for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_pr_review_details',
    description: 'Get the full details of a single MR review note by its ID.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      review_id: { type: 'number', required: !0, description: 'Note/review ID' },
    },
  },
  {
    name: 'gitlab_get_org_variables',
    description: 'List group-level GitLab CI/CD variables.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { org: { type: 'string', required: !0, description: 'GitLab group name' } },
  },
  {
    name: 'gitlab_get_repo_autolinks',
    description: 'List autolink references configured for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_check_run_details',
    description: 'Get full details of a specific CI job including status, conclusion, and output.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      check_run_id: { type: 'number', required: !0, description: 'Job ID' },
    },
  },
  {
    name: 'gitlab_create_repo',
    description: 'Create a new GitLab repository for the authenticated user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      name: { type: 'string', required: !0, description: 'Repository name' },
      description: { type: 'string', required: !1, description: 'Short description' },
      private: {
        type: 'boolean',
        required: !1,
        description: 'Set true to create as private (default false)',
      },
      auto_init: { type: 'boolean', required: !1, description: 'Initialize with a README' },
    },
  },
  {
    name: 'gitlab_update_repo',
    description:
      'Update repository settings such as description, homepage, visibility, or default branch.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      description: { type: 'string', required: !1, description: 'New description' },
      homepage: { type: 'string', required: !1, description: 'Homepage URL' },
      private: { type: 'boolean', required: !1, description: 'Set visibility (true = private)' },
      default_branch: { type: 'string', required: !1, description: 'New default branch' },
      has_issues: { type: 'boolean', required: !1, description: 'Enable or disable issues' },
      has_wiki: { type: 'boolean', required: !1, description: 'Enable or disable wiki' },
      has_projects: { type: 'boolean', required: !1, description: 'Enable or disable snippets' },
    },
  },
  {
    name: 'gitlab_delete_repo',
    description: 'Permanently delete a GitLab repository. This action is irreversible.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_repo_contents',
    description: 'List directory contents or get file metadata at a path in a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      path: { type: 'string', required: !1, description: 'Path within the repo (empty for root)' },
      ref: { type: 'string', required: !1, description: 'Branch, tag, or SHA (optional)' },
    },
  },
  {
    name: 'gitlab_create_or_update_file',
    description: 'Create or update a single file in a repository via a commit.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      file_path: {
        type: 'string',
        required: !0,
        description: 'Path to the file (e.g. src/index.js)',
      },
      message: { type: 'string', required: !0, description: 'Commit message' },
      content: { type: 'string', required: !0, description: 'File content (plain text or base64)' },
      sha: {
        type: 'string',
        required: !1,
        description: 'Blob SHA of the file being replaced (required for updates)',
      },
      branch: {
        type: 'string',
        required: !1,
        description: 'Branch to commit to (defaults to default branch)',
      },
    },
  },
  {
    name: 'gitlab_delete_file',
    description: 'Delete a file from a repository via a commit.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      file_path: { type: 'string', required: !0, description: 'Path to the file to delete' },
      message: { type: 'string', required: !0, description: 'Commit message' },
      sha: { type: 'string', required: !0, description: 'Blob SHA of the file' },
      branch: {
        type: 'string',
        required: !1,
        description: 'Branch to commit to (defaults to default branch)',
      },
    },
  },
  {
    name: 'gitlab_get_commit_comments',
    description: 'Get all comments on a specific commit.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      sha: { type: 'string', required: !0, description: 'Commit SHA' },
    },
  },
  {
    name: 'gitlab_create_commit_comment',
    description: 'Post a comment on a specific commit.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      sha: { type: 'string', required: !0, description: 'Commit SHA' },
      body: { type: 'string', required: !0, description: 'Comment body' },
      path: {
        type: 'string',
        required: !1,
        description: 'File path to attach comment to (optional)',
      },
      position: { type: 'number', required: !1, description: 'Line index in the diff (optional)' },
    },
  },
  {
    name: 'gitlab_dismiss_pr_review',
    description: 'Dismiss a submitted merge request review with a message.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      pr_number: { type: 'number', required: !0, description: 'Merge request number' },
      review_id: { type: 'number', required: !0, description: 'Note/review ID' },
      message: { type: 'string', required: !0, description: 'Reason for dismissal' },
    },
  },
  {
    name: 'gitlab_cancel_workflow_run',
    description: 'Cancel a running GitLab CI/CD pipeline.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      run_id: { type: 'number', required: !0, description: 'Pipeline ID' },
    },
  },
  {
    name: 'gitlab_rerun_workflow_run',
    description: 'Retry a failed or cancelled GitLab CI/CD pipeline.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      run_id: { type: 'number', required: !0, description: 'Pipeline ID' },
    },
  },
  {
    name: 'gitlab_list_workflow_run_artifacts',
    description: 'List build artifacts produced by a pipeline run.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      run_id: { type: 'number', required: !0, description: 'Pipeline ID' },
      count: { type: 'number', required: !1, description: 'Max artifacts to return (default 20)' },
    },
  },
  {
    name: 'gitlab_check_if_starred',
    description: 'Check whether the authenticated user has starred a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_follow_user',
    description: 'Follow a GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username to follow' },
    },
  },
  {
    name: 'gitlab_unfollow_user',
    description: 'Unfollow a GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      username: { type: 'string', required: !0, description: 'GitLab username to unfollow' },
    },
  },
  {
    name: 'gitlab_get_issue_events',
    description: 'Get activity events for a GitLab issue.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number' },
      count: { type: 'number', required: !1, description: 'Max events to return (default 30)' },
    },
  },
  {
    name: 'gitlab_update_gist',
    description: 'Update the description or files of an existing GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      gist_id: { type: 'string', required: !0, description: 'Snippet ID' },
      description: { type: 'string', required: !1, description: 'New description' },
      files: {
        type: 'string',
        required: !1,
        description: 'JSON object of file changes e.g. {"file.js":{"content":"..."}}',
      },
    },
  },
  {
    name: 'gitlab_delete_gist',
    description: 'Permanently delete a GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { gist_id: { type: 'string', required: !0, description: 'Snippet ID to delete' } },
  },
  {
    name: 'gitlab_transfer_issue',
    description: 'Transfer a GitLab issue to another repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'Current repo owner' },
      repo: { type: 'string', required: !0, description: 'Current repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue number to transfer' },
      new_owner: { type: 'string', required: !0, description: 'Owner of the target repository' },
    },
  },
  {
    name: 'gitlab_replace_topics',
    description: 'Replace all topics on a GitLab repository with a new set.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      topics: {
        type: 'string',
        required: !0,
        description: 'Comma-separated list of topic names (pass empty string to clear all)',
      },
    },
  },
  {
    name: 'gitlab_get_authenticated_user',
    description: 'Get the full profile of the currently authenticated GitLab user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_update_comment',
    description: 'Edit the body of an existing issue or merge request comment.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      comment_id: { type: 'number', required: !0, description: 'Comment ID to edit' },
      body: { type: 'string', required: !0, description: 'New comment body in markdown' },
    },
  },
  {
    name: 'gitlab_delete_comment',
    description: 'Permanently delete an issue or merge request comment.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      comment_id: { type: 'number', required: !0, description: 'Comment ID to delete' },
    },
  },
  {
    name: 'gitlab_add_reaction_to_issue',
    description: 'Add an emoji reaction to a GitLab issue or merge request.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      issue_number: { type: 'number', required: !0, description: 'Issue or merge request number' },
      content: {
        type: 'string',
        required: !0,
        description: 'Reaction: +1, -1, laugh, hooray, confused, heart, rocket, or eyes',
      },
    },
  },
  {
    name: 'gitlab_add_reaction_to_comment',
    description: 'Add an emoji reaction to an issue or merge request comment.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      comment_id: { type: 'number', required: !0, description: 'Comment ID' },
      content: {
        type: 'string',
        required: !0,
        description: 'Reaction: +1, -1, laugh, hooray, confused, heart, rocket, or eyes',
      },
    },
  },
  {
    name: 'gitlab_get_code_scanning_alerts',
    description: 'List SAST security alerts for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      state: { type: 'string', required: !1, description: 'open (default), dismissed, or fixed' },
    },
  },
  {
    name: 'gitlab_get_secret_scanning_alerts',
    description: 'List secret scanning alerts for a GitLab repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      state: { type: 'string', required: !1, description: 'open (default) or resolved' },
    },
  },
  {
    name: 'gitlab_delete_workflow_run',
    description: 'Delete a completed GitLab CI/CD pipeline record.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      run_id: { type: 'number', required: !0, description: 'Pipeline ID' },
    },
  },
  {
    name: 'gitlab_get_workflow_run_jobs',
    description: 'List all jobs (and their steps) for a GitLab CI/CD pipeline.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
      run_id: { type: 'number', required: !0, description: 'Pipeline ID' },
      filter: { type: 'string', required: !1, description: 'latest (default) or all' },
    },
  },
  {
    name: 'gitlab_check_team_membership',
    description: "Check a user's membership status and role in a specific group.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      org: { type: 'string', required: !0, description: 'GitLab group name' },
      team_slug: { type: 'string', required: !0, description: 'Subgroup slug' },
      username: { type: 'string', required: !0, description: 'GitLab username to check' },
    },
  },
  {
    name: 'gitlab_list_gist_comments',
    description: 'List all comments on a GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      gist_id: { type: 'string', required: !0, description: 'Snippet ID' },
      count: { type: 'number', required: !1, description: 'Max comments to return (default 30)' },
    },
  },
  {
    name: 'gitlab_create_gist_comment',
    description: 'Post a comment on a GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      gist_id: { type: 'string', required: !0, description: 'Snippet ID' },
      body: { type: 'string', required: !0, description: 'Comment body in markdown' },
    },
  },
  {
    name: 'gitlab_get_repo_actions_permissions',
    description: 'Get the GitLab CI/CD permissions policy for a repository.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      owner: { type: 'string', required: !0, description: 'GitLab username or group' },
      repo: { type: 'string', required: !0, description: 'Repository name' },
    },
  },
  {
    name: 'gitlab_get_org_webhooks',
    description: 'List webhooks configured at the group level.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { org: { type: 'string', required: !0, description: 'GitLab group name' } },
  },
  {
    name: 'gitlab_list_user_repo_invitations',
    description:
      'List all pending repository collaboration invitations for the authenticated user.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {},
  },
  {
    name: 'gitlab_accept_repo_invitation',
    description: 'Accept a pending repository collaboration invitation.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { invitation_id: { type: 'number', required: !0, description: 'Invitation ID' } },
  },
  {
    name: 'gitlab_decline_repo_invitation',
    description: 'Decline a pending repository collaboration invitation.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { invitation_id: { type: 'number', required: !0, description: 'Invitation ID' } },
  },
  {
    name: 'gitlab_get_user_public_keys',
    description: "List a GitLab user's public SSH keys.",
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { username: { type: 'string', required: !0, description: 'GitLab username' } },
  },
  {
    name: 'gitlab_star_gist',
    description: 'Star or unstar a GitLab Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: {
      gist_id: { type: 'string', required: !0, description: 'Snippet ID' },
      action: { type: 'string', required: !1, description: 'star (default) or unstar' },
    },
  },
  {
    name: 'gitlab_check_gist_starred',
    description: 'Check whether the authenticated user has starred a specific Snippet.',
    category: 'gitlab',
    connectorId: 'gitlab',
    parameters: { gist_id: { type: 'string', required: !0, description: 'Snippet ID' } },
  },
];
export default GITLAB_TOOLS;
