/**
 * Docs.mjs — Auto-generates PACKAGES.md from source.
 *
 * For every package in Packages/ it extracts:
 *   - Package name and description (from JSDoc in Index.js)
 *   - IPC channels (parsed from ipcHandlers array)
 *   - Internal structure (Core, UI, IPC, I18n presence)
 *   - Shared dependencies used
 *
 * Usage:
 *   node Scripts/Docs.mjs
 *
 * Output:
 *   PACKAGES.md — committed to the repo and kept up to date via CI.
 */

import path from 'node:path';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGES_DIR = path.join(ROOT, 'Packages');
const OUTPUT_FILE = path.join(ROOT, 'PACKAGES.md');

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function dirExists(dirPath) {
  try {
    const stats = await stat(dirPath);
    return stats.isDirectory();
  } catch {
    return false;
  }
}

async function fileExists(filePath) {
  try {
    const stats = await stat(filePath);
    return stats.isFile();
  } catch {
    return false;
  }
}

function extractJsDocDescription(source) {
  const match = source.match(/\/\*\*\s*\n\s*\*\s*([^\n*][^\n]*)/);
  return match ? match[1].trim() : null;
}

function extractIpcChannels(source) {
  const channels = [];
  const pattern = /channel:\s*['"]([^'"]+)['"]/g;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    channels.push(match[1]);
  }
  return [...new Set(channels)];
}

function extractSharedImports(source) {
  const shared = new Set();
  const pattern = /from\s+['"][^'"]*\/Shared\/([^/'"]+)/g;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    shared.add(match[1]);
  }
  return [...shared];
}

// ─── Package analyser ─────────────────────────────────────────────────────────

async function analysePackage(name) {
  const pkgDir = path.join(PACKAGES_DIR, name);
  const indexPath = path.join(pkgDir, 'Index.js');

  const hasIndex = await fileExists(indexPath);
  const hasCore = await dirExists(path.join(pkgDir, 'Core'));
  const hasUI = await dirExists(path.join(pkgDir, 'UI'));
  const hasIPC = await dirExists(path.join(pkgDir, 'IPC'));
  const hasI18n = await dirExists(path.join(pkgDir, 'I18n'));

  let description = null;
  let channels = [];
  let sharedDeps = [];

  if (hasIndex) {
    const source = await readFile(indexPath, 'utf8');
    description = extractJsDocDescription(source);
    channels = extractIpcChannels(source);
    sharedDeps = extractSharedImports(source);
  }

  // Also scan Core and IPC folders for more channels/shared imports
  for (const subDir of ['Core', 'IPC']) {
    const subDirPath = path.join(pkgDir, subDir);
    if (!(await dirExists(subDirPath))) {
      continue;
    }

    const entries = await readdir(subDirPath, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith('.js')) {
        continue;
      }

      const src = await readFile(path.join(subDirPath, entry.name), 'utf8');
      channels.push(...extractIpcChannels(src));

      for (const dep of extractSharedImports(src)) {
        sharedDeps.push(dep);
      }
    }
  }

  channels = [...new Set(channels)].sort();
  sharedDeps = [...new Set(sharedDeps)].sort();

  return { name, description, hasCore, hasUI, hasIPC, hasI18n, channels, sharedDeps };
}

// ─── Markdown renderer ────────────────────────────────────────────────────────

function renderPackageRow(pkg) {
  const structure = [
    pkg.hasCore ? '`Core`' : null,
    pkg.hasUI ? '`UI`' : null,
    pkg.hasIPC ? '`IPC`' : null,
    pkg.hasI18n ? '`I18n`' : null,
  ]
    .filter(Boolean)
    .join(' ');

  const desc = pkg.description ?? '—';
  return `| **${pkg.name}** | ${desc} | ${structure || '—'} |`;
}

function renderChannelRows(pkg) {
  if (pkg.channels.length === 0) {
    return [];
  }

  return pkg.channels.map((ch) => `| \`${ch}\` | ${pkg.name} |`);
}

function render(packages) {
  const timestamp = new Date().toUTCString();
  const total = packages.length;
  const withUI = packages.filter((p) => p.hasUI).length;
  const allChannels = packages.flatMap((p) => p.channels);

  const lines = [
    `# Package Registry`,
    ``,
    `> Auto-generated by \`node Scripts/Docs.mjs\` — do not edit by hand.  `,
    `> Last updated: ${timestamp}`,
    ``,
    `**${total}** packages · **${withUI}** with UI · **${allChannels.length}** IPC channels`,
    ``,
    `---`,
    ``,
    `## Packages`,
    ``,
    `| Package | Description | Structure |`,
    `|---|---|---|`,
    ...packages.map(renderPackageRow),
    ``,
    `---`,
    ``,
    `## IPC Channel Reference`,
    ``,
    `| Channel | Package |`,
    `|---|---|`,
    ...packages.flatMap(renderChannelRows),
    ``,
    `---`,
    ``,
    `## Shared Module Usage`,
    ``,
    `| Package | Uses from Shared |`,
    `|---|---|`,
    ...packages
      .filter((p) => p.sharedDeps.length > 0)
      .map((p) => `| ${p.name} | ${p.sharedDeps.map((d) => `\`${d}\``).join(', ')} |`),
    ``,
  ];

  return lines.join('\n');
}

// ─── Runner ───────────────────────────────────────────────────────────────────

async function run() {
  console.log('[Docs] Scanning Packages/...');

  const entries = await readdir(PACKAGES_DIR, { withFileTypes: true });
  const names = entries.filter((e) => e.isDirectory()).map((e) => e.name);

  console.log(`[Docs] Found ${names.length} packages`);

  const packages = await Promise.all(names.map(analysePackage));
  packages.sort((a, b) => a.name.localeCompare(b.name));

  const markdown = render(packages);
  await writeFile(OUTPUT_FILE, markdown, 'utf8');

  const totalChannels = packages.reduce((sum, p) => sum + p.channels.length, 0);
  console.log(
    `[Docs] ✓ PACKAGES.md written — ${packages.length} packages, ${totalChannels} IPC channels`,
  );
}

run().catch((error) => {
  console.error('[Docs] Fatal error:', error);
  process.exit(1);
});
